# Generated by Django 5.2.3 on 2025-06-22 23:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pintor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.IntegerField()),
                ('obras', models.IntegerField()),
                ('obra_destacada', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('tecnica_utilizada', models.CharField(max_length=100)),
                ('movimiento', models.CharField(max_length=100)),
                ('texto2', models.TextField()),
                ('paleta', models.CharField(max_length=100)),
                ('analisis', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
