# Generated by Django 5.2.3 on 2025-06-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintor',
            name='activo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pintor',
            name='obras',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
