# Generated by Django 5.2.3 on 2025-06-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_pintor_activo_alter_pintor_obras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pintor',
            old_name='analisis',
            new_name='acerca_del_movimiento',
        ),
        migrations.RenameField(
            model_name='pintor',
            old_name='texto',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='pintor',
            old_name='activo',
            new_name='cantidad_de_obras',
        ),
        migrations.RenameField(
            model_name='pintor',
            old_name='texto2',
            new_name='nacionalidad',
        ),
        migrations.RenameField(
            model_name='pintor',
            old_name='paleta',
            new_name='paleta_utilizada',
        ),
        migrations.RenameField(
            model_name='pintor',
            old_name='obras',
            new_name='tiempo_activo',
        ),
    ]
