# Generated by Django 5.2.3 on 2025-06-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_analisis_pintor_acerca_del_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintor',
            name='nacionalidad',
            field=models.CharField(max_length=20),
        ),
    ]
