# Generated by Django 5.2.3 on 2025-06-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_pintor_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='artistas/'),
        ),
        migrations.AddField(
            model_name='pintor',
            name='informacion_adicional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
